name: Build Extension and deploy to dev.pot.ch

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        run build

    - name: Create Zip file
      run: |
        mkdir target
        mv build target
        mv images target
        mv inc target
        mv languages target
        mv scripts target
        mv styles target
        mv vendor target
        mv *.md target
        mv *.php target
        cd target
        zip -r ../pot.zip *
        
        
        
        
